services:
  reverse_proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend

  ws1:
    image: nginx:alpine
    volumes:
      - ./my-web-1:/usr/share/nginx/html
    networks:
      - backend

  ws2:
    image: nginx:alpine
    volumes:
      - ./my-web-2:/usr/share/nginx/html
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
